### ISSUE TITLE
Verify cannot delete personal accounts with signatures attached

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#29]
Laura suggest that "use the force" is perhaps still not enough as you'd be changing history.

**Comment by ericvaandering** [comment]
And there is no use the force option. We can add a check on existing signatures before running the delete code

**Comment by ericvaandering** [comment]
The check on signoff IDs was added to the FNAL_sso branch about halfway into the development process, so it's there. 

However, the signoff IDs are just a simple check: https://github.com/ericvaandering/DocDB/blob/fnal_sso/DocDB/cgi/SignoffSQL.pm#L185

This will pick up SignoffIDs from Obsolete documents as well.

Here's my proposal. I think this is unlikely to be a real operational issue that someone wants to delete their account who, 

1. was never asked to sign a real document
1. somehow was asked to sign one by mistake
1. that document had its metadata changed to remove them as a signer

That's the only case where this would fail to be able to delete when legitimately it probably should.

So I'd suggest we open another issue for that case, just noting it, and put it in 8.8.10 for consideration. Sound good?

**Comment by lauramengel** [comment]
I did not receive an email with your suggestion to move this to 8.8.10,
(possibly because you created this issue item initially instead of me),
so that is why I did not answer until just now.

Was not able to delete personal accounts needing to sign future/current/(un)approved/future docs.
So this works.

Low priority: the error message showed html for the signature report link instead of the link.

You cannot delete this account, it has \<a href="https://test-docdbdev.fnal.gov/cgi-bin/private/SignatureReport?emailuserid=650"\>signed or needs to sign documents\</a\>. You can disable ...

OK on moving to 8.8.10: can't delete user who is supposed to sign only obsolete version.
You can move fixing the html in the error message to 8.8.10 or do here.

**Comment by ericvaandering** [comment]
Ah, is that error message in the Error report? I think we removed the ability to have HTML in those messages some time ago. I may need to, instead, explain how to find the documents involved rather than give a link. 

In any case I will fix it after lunch.

**Comment by lauramengel** [comment]
The message is on the results screen after submitting to delete an account.
(This is probably what you meant by the error report.)

If it can not be an active link, then the next best thing would
be to keep the URL, but just take the html tags out.
Having the URL for the signature report is useful.

I will make a new issue for the remaining item as you suggested
(for 8.8.10 consideration).

**Comment by ericvaandering** [comment]
Right, everything that goes into the error, warning, or action reports cannot be HTML. I think we removed that for XSS reasons.

I updated and pushed a fix as you suggested.

**Comment by lauramengel** [comment]
Rewording / removal of raw html looks good. Closing issue.
Issue #73 was opened for the issue of not checking obsolete
versions of documents for signatures.
