### ISSUE TITLE
XSS problem with Active Search

### ISSUE THREAD

**Issue by ericvaandering** [ericvaandering/DocDB#37]
1. Use SelectPrefs to set to active search: https://test-docdbdevcert.fnal.gov/cgi-bin/cert/SelectPrefs
2. Click "new", "Hello" shows up.

**Comment by ericvaandering** [comment]
Waiting on RITM0653690

**Comment by lauramengel** [comment]
I have not seen any JS popups since you changed this. Closing issue.
(though it makes the active search author list truncate,
but only with the bad data, so if we delete, that should be ok)

- No JS run (no popup) with existing authors with embedded JS
   in doc, doc modify, author list, add author, add author admin pages,
   for all 3 auther methods (active search, add from list, ordered list)

- No JS run (no popup) with new authors added with embedded JS
   in doc, doc modify, author list, add author, add author admin pages,
   for all 3 author methods (active search, add from list, ordered list)

- No JS run with new Topic with JS in topic admin, topic list, search list,
   event, modify doc, create doc
