### ISSUE TITLE
RetrieveArchive 8.8.9 includes unwanted file in tar/zip archives

### ISSUE THREAD

**Issue by lauramengel** [ericvaandering/DocDB#91]
Please "--exclude=filenamehere" or or    "-x filenamehere"
in the 4 tar/zip system commands in RetrieveArchive.

The code in 8.7.23 already does this.

**Comment by lauramengel** [comment]
From: Eric
>  I suspect I missed a forward porting of a patch. Good to know, should be trivial

Sounds good. Is there some way to figure out if we missed any other patches?

**Comment by ericvaandering** [comment]
Actually, I did not miss the patch. Looking at FSUtilities.pm it seems the file can be included if you are using the combination of regular tar and gzip, but not if $GTar is defined. Can you check what you have in ProjectGlobals.pm? You should have GNU Tar on the system which can do this in one go rather than relying on piping UNIX tar into gzip. 

I'll check if UNIX tar has the correct option.

**Comment by ericvaandering** [comment]
Fixed by #94 

There isn't really a way to easily see missed commits this old. We were on CVS which doesn't give a nice history (you can't actually see merges) and the code has diverged too much.
